### ISSUE TITLE
Join rosetta-rs?

### ISSUE THREAD

**Issue by epage** [djkoloski/rust_serialization_benchmark#32]
I've been maintaining several benchmark repos based off of [`template-benchmarks-rs`](https://github.com/djc/template-benchmarks-rs).  I've noticed there are [several other benchmark repos](https://www.reddit.com/r/rust/comments/w24rmg/github_epageparsebenchmarksrs/ignzypd/) that are hard to know about.

I've created rosetta-rs org as a place for these repos if the authors so choose to
- Increase discoverability
- Improve bus factor

See the [meta repo](https://github.com/rosetta-rs/team) for more details

Interested in collaborating?

**Comment by djkoloski** [comment]
Sorry for the delay in responding. I'm not _uninterested_ in joining a dedicated org, but I'm not sold on the value proposition:

> Increase discoverability

Instead of moving repositories under a shared org, it seems like this could be accomplished by just listing and linking. There are already plenty of "awesome rust crates" repos, though I agree that many of them fail to back up recommendations with hard data. What discoverability advantages would a shared org have over listing and linking?

> Improve bus factor

I like the idea of improving the bus factor, and I see how an org can help with that. However, bus factor isn't _really_ that much of a concern to me. Even in the worst case scenario, someone could fork the repo and continue working on it.

> Interested in collaborating?

Yes! I think that there's potential for some valuable collaborative work here. Here are some ideas that sound appealing to me:

- Pooling development resources to foster cross-collaboration and stimulate investment into existing benchmark repos.
- Networking developers together to accurately grade the quality of benchmark data. Kind of like a web of trust for hard numbers.
- Consolidating data to make it more useful and accessible. Having a standard format for benchmark data could enable users to explore that information through a friendly interface with quality visualization.

These ideas raise a lot of additional questions, but pursuing some of them sounds exciting and beneficial for the community. Feel free to get in touch directly (via [email](djkoloski@gmail.com), [dm](https://twitter.com/david_koloski), or however else) if you'd like to chat some more. I'm going to close this issue for now and if we continue the discussion elsewhere (e.g. in the rosetta-rs repo) I'll link that conversation from here.
